version: '3'

services:
  frontend:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development